### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.keyvault.v7_0.models.key_vault_error_py3.KeyVaultError
  - azure.keyvault.v7_0.models.key_vault_error_py3.KeyVaultErrorException
  fullName: azure.keyvault.v7_0.models.key_vault_error_py3
  langs:
  - python
  module: azure.keyvault.v7_0.models.key_vault_error_py3
  name: key_vault_error_py3
  type: module
  uid: azure.keyvault.v7_0.models.key_vault_error_py3
references:
- fullName: azure.keyvault.v7_0.models.key_vault_error_py3.KeyVaultError
  isExternal: false
  name: KeyVaultError
  parent: azure.keyvault.v7_0.models.key_vault_error_py3
  uid: azure.keyvault.v7_0.models.key_vault_error_py3.KeyVaultError
- fullName: azure.keyvault.v7_0.models.key_vault_error_py3.KeyVaultErrorException
  isExternal: false
  name: KeyVaultErrorException
  parent: azure.keyvault.v7_0.models.key_vault_error_py3
  uid: azure.keyvault.v7_0.models.key_vault_error_py3.KeyVaultErrorException
